### ISSUE TITLE
Difference between video and clips

### ISSUE THREAD

**Issue by 2000ZRL** [how2sign/how2sign-data#2]
Dear authors,

I know that each clip is corresponding to a sentence, but what is the content of videos? A paragraph? I will appreciate it if you can help me.

**Comment by Shreeshail-Hingane** [comment]
I have the same query. My guess is that it is the clips (and not the videos) that form the How2Sign dataset, since the English Translation files and the OpenPose data files (provided at https://how2sign.github.io/#download) correspond to data from the clips. 
I am assuming that the video data is only provided as a reference and comprises of the original How2 dataset, and is not needed in its entirety for the How2Sign dataset.
Correct me if I am wrong.

**Comment by Shreeshail-Hingane** [comment]
I know that the clips are just sentences from the videos. But the video files have much larger size than the clip files. Does this mean that the clips are a small subset of the video files?

**Comment by how2sign** [comment]
Thank you for your questions!

To clarify your questions:

The content of the videos:
Given that the How2Sign was built on top of the How2, and that the How2 contains instructional videos from Youtube, the content of the "videos" in the How2Sign is the ASL translation (performed by a signer) of the entire instructional videos*.

Clips:
After recording the whole video, we split them into sentences. These sentences were the ones available on the How2**.
Thus, the clips contain sentences in ASL, that correspond to the English transcriptions from the How2.

* We selected a subset of the How2 to build the How2Sign. You can find more info about it in the paper.
** It is important to have in mind that not all the sentences in the How2 dataset were available. We used just the ones that were available, making the content of the videos larger than the sentences.
